apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: auth-kv-istio-ingress
  namespace: istio-system
spec:
  method: kubernetes
  mount: kubernetes-proj
  namespace: admin
  kubernetes:
    role: istio-ingress-role
    serviceAccount: istio-ingressgateway-service-account
    audiences:
    - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: static-sec-cred-c
  namespace: istio-system
spec:
  type: kv-v2
  namespace: admin
  mount: proj-kv
  path: cred-c
  destination:
    name: cred-c
    create: true
    type: "kubernetes.io/tls"
  refreshAfter: 30s 
  vaultAuthRef: auth-kv-istio-ingress

